### ISSUE TITLE
Can not see analyze

### ISSUE THREAD

**Issue by volcano1995** [StanfordSNR/pantheon#58]
When I run src/analysis/analyze.py --data-dir DIR, some error occurs:
$ python /home/volcano/pantheon/src/analysis/plot.py --data-dir DIR
Traceback (most recent call last):
  File "/home/volcano/pantheon/src/analysis/plot.py", line 356, in <module>
    main()
  File "/home/volcano/pantheon/src/analysis/plot.py", line 352, in main
    Plot(args).run()
  File "/home/volcano/pantheon/src/analysis/plot.py", line 27, in __init__
    meta = utils.load_test_metadata(metadata_path)
  File "/home/volcano/pantheon/src/helpers/utils.py", line 81, in load_test_metadata
    with open(metadata_path) as metadata:
IOError: [Errno 2] No such file or directory: '/home/volcano/pantheon/DIR/pantheon_metadata.json'
Traceback (most recent call last):
  File "src/analysis/analyze.py", line 33, in <module>
    main()
  File "src/analysis/analyze.py", line 28, in main
    check_call(plot_cmd)
  File "/home/volcano/pantheon/src/helpers/subprocess_wrappers.py", line 24, in check_call
    return subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/home/volcano/pantheon/src/analysis/plot.py', '--data-dir', 'DIR']' returned non-zero exit status 1

Anyone know how to solve it? Thanks!

**Comment by samar1tan** [comment]
The *DIR* options provided for  `analyze.py` should be replaced by the actual path in which test logs are stored.
