### ISSUE TITLE
Errors running webrtc and quic

### ISSUE THREAD

**Issue by volcano1995** [StanfordSNR/pantheon#61]
When I run all scheme, the webrtc and quic failed.
The problem of quic is below:

[tcm] tunnel 1 python /home/volcano/pantheon/src/wrappers/quic.py sender 45905
[0525/120135.439522:ERROR:nss_util.cc(706)] Error initializing NSS with a persistent database (sql:/home/volcano/.pki/nssdb): NSS error code: -8015
[tsm] tunnel 1 python /home/volcano/pantheon/src/wrappers/quic.py receiver 100.64.0.4 45905
[0525/120137.126924:ERROR:nss_util.cc(706)] Error initializing NSS with a persistent database (sql:/home/volcano/.pki/nssdb): NSS error code: -8015
[0525/120137.162003:ERROR:cert_verify_proc_nss.cc(912)] CERT_PKIXVerifyCert for www.example.org failed err=-8179
[0525/120137.162383:WARNING:proof_verifier_chromium.cc(466)] Failed to verify certificate chain: net::ERR_CERT_AUTHORITY_INVALID
Failed to connect to 100.64.0.4:45905. Error: QUIC_PROOF_INVALID
[0525/120138.188233:ERROR:nss_util.cc(706)] Error initializing NSS with a persistent database (sql:/home/volcano/.pki/nssdb): NSS error code: -8015
[0525/120138.205257:ERROR:cert_verify_proc_nss.cc(912)] CERT_PKIXVerifyCert for www.example.org failed err=-8179
[0525/120138.205596:WARNING:proof_verifier_chromium.cc(466)] Failed to verify certificate chain: net::ERR_CERT_AUTHORITY_INVALID
Failed to connect to 100.64.0.4:45905. Error: QUIC_PROOF_INVALID
[0525/120139.226945:ERROR:nss_util.cc(706)] Error initializing NSS with a persistent database (sql:/home/volcano/.pki/nssdb): NSS error code: -8015
[0525/120139.245299:ERROR:cert_verify_proc_nss.cc(912)] CERT_PKIXVerifyCert for www.example.org failed err=-8179
[0525/120139.245938:WARNING:proof_verifier_chromium.cc(466)] Failed to verify certificate chain: net::ERR_CERT_AUTHORITY_INVALID
Failed to connect to 100.64.0.4:45905. Error: QUIC_PROOF_INVALID
[0525/120140.285157:ERROR:nss_util.cc(706)] Error initializing NSS with a persistent database (sql:/home/volcano/.pki/nssdb): NSS error code: -8015
[0525/120140.302003:ERROR:cert_verify_proc_nss.cc(912)] CERT_PKIXVerifyCert for www.example.org failed err=-8179
[0525/120140.302479:WARNING:proof_verifier_chromium.cc(466)] Failed to verify certificate chain: net::ERR_CERT_AUTHORITY_INVALID
Failed to connect to 100.64.0.4:45905. Error: QUIC_PROOF_INVALID
[0525/120141.343799:ERROR:nss_util.cc(706)] Error initializing NSS with a persistent database (sql:/home/volcano/.pki/nssdb): NSS error code: -8015
[0525/120141.361345:ERROR:cert_verify_proc_nss.cc(912)] CERT_PKIXVerifyCert for www.example.org failed err=-8179
[0525/120141.361851:WARNING:proof_verifier_chromium.cc(466)] Failed to verify certificate chain: net::ERR_CERT_AUTHORITY_INVALID
Failed to connect to 100.64.0.4:45905. Error: QUIC_PROOF_INVALID
[tsm] halt
kill_proc_group: killed process group with pgid 67921

I try to run webrtc only, the error is below, without sudo the result is same:
volcano@lican:~/pantheon$ sudo src/wrappers/quic.py run_first
sender
volcano@lican:~/pantheon$ sudo src/wrappers/quic.py sender 9999
Traceback (most recent call last):
  File "src/wrappers/quic.py", line 123, in <module>
    main()
  File "src/wrappers/quic.py", line 106, in main
    check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/volcano/pantheon/third_party/proto-quic/src/out/Default/quic_server', '--port=9999', '--quic_response_cache_dir=/home/volcano/pantheon/third_party/proto-quic/www.example.org', '--certificate_file=/home/volcano/pantheon/src/wrappers/quic-certs/leaf_cert.pem', '--key_file=/home/volcano/pantheon/src/wrappers/quic-certs/leaf_cert.pkcs8']' returned non-zero exit status -11

The problem of webrtc is:

[tcm] tunnel 1 python /home/volcano/pantheon/src/wrappers/webrtc.py sender 37155
Traceback (most recent call last):
  File "/home/volcano/pantheon/src/wrappers/webrtc.py", line 93, in <module>
    main()
  File "/home/volcano/pantheon/src/wrappers/webrtc.py", line 61, in main
    Popen(['node', signaling_server_src, args.port])
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[tsm] tunnel 1 python /home/volcano/pantheon/src/wrappers/webrtc.py receiver 100.64.0.4 37155
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(chromium-browser:68346): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(chromium-browser:68346): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(chromium-browser:68346): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
ATTENTION: default value of option force_s3tc_enable overridden by environment.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[68384:68384:0525/120244.903647:ERROR:gl_surface_glx.cc(126)] Failed to get GLXConfig
[68384:68384:0525/120244.903679:ERROR:gl_surface_glx.cc(448)] CreateDummyWindow(gfx::GetXDisplay()) failed
[68384:68384:0525/120244.903686:ERROR:gl_initializer_x11.cc(147)] GLSurfaceGLX::InitializeOneOff failed.
[68384:68384:0525/120244.910566:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
[68346:68473:0525/120245.007834:ERROR:bus.cc(396)] Failed to connect to the bus: Failed to connect to socket /tmp/dbus-bgvywDqBWN: Connection refused
Gkr-Message: couldn't connect to dbus session bus: Failed to connect to socket /tmp/dbus-bgvywDqBWN: Connection refused

(chromium-browser:68346): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Could not connect: Connection refused
[1:8:0525/120245.286976:ERROR:command_buffer_proxy_impl.cc(105)] ContextResult::kTransientFailure: Shared memory region is not valid

I am sure I have install all deps of webrtc.

Anyone know how to solve them? Thanks!

**Comment by francisyyan** [comment]
Could you please send these questions to our Google group (pantheon-stanford@googlegroups.com) instead (unless they are real issues)? Thank you!
