### ISSUE TITLE
pantheon: src/experiments/test.py local --all cann't run

### ISSUE THREAD

**Issue by Allen-kevin** [StanfordSNR/pantheon#67]
Hi ,i have a problem, when I test schemes in emulated networks locally by run:
src/experiments/test.py local --all
$ /users/kai/pantheon/src/experiments/git_summary.sh
Testing scheme fillp_sheep for experiment run 1/1...
$ /users/kai/pantheon/src/wrappers/fillp_sheep.py run_first
[tunnel server manager (tsm)] $ python /users/kai/pantheon/src/experiments/tunnel_manager.py
tunnel manager is running
prompt [tsm]
/users/kai/pantheon/src/experiments/12mbps.trace --uplink-log=/users/kai/pantheon/src/experiments/data/fillp_sheep_mm_datalink_run1.log --downlink-log=/users/kai/pantheon/src/experiments/data/fillp_sheep_mm_acklink_run1.log python /users/kai/pantheon/src/experiments/tunnel_manager.py
kill_proc_group: killed process group with pgid 62456
tunnel_manager: caught signal 15 and cleaned up

Traceback (most recent call last):
File "src/experiments/test.py", line 808, in main
run_tests(args)
File "src/experiments/test.py", line 782, in run_tests
Test(args, run_id, cc).run()
File "src/experiments/test.py", line 735, in run
if not self.run_congestion_control():
File "src/experiments/test.py", line 686, in run_congestion_control
return self.run_with_tunnel()
File "src/experiments/test.py", line 533, in run_with_tunnel
ts_manager, tc_manager = self.run_tunnel_managers()
File "src/experiments/test.py", line 297, in run_tunnel_managers
preexec_fn=os.setsid)
File "/users/kai/pantheon/src/helpers/subprocess_wrappers.py", line 34, in Popen
return subprocess.Popen(cmd, **kwargs)
File "/usr/lib/python2.7/subprocess.py", line 711, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
Error in tests!

I have followed the instructions in README, and not find any error until i run src/experiments/test.py local --all

**Comment by francisyyan** [comment]
Hello -- this is not an issue as far as I know. Please send the question to our Google group (if you haven't done so) and I will reply you there. Thank you!
