### ISSUE TITLE
run indigo error?

### ISSUE THREAD

**Issue by BetterYong** [StanfordSNR/pantheon#69]
Hello, I ran into an error while running indigo. I follow these steps:
`git clone https://github.com/StanfordSNR/pantheon.git
git submodule update --init --recursive  # or tools/fetch_submodules.sh
src/experiments/setup.py --install-deps  --all
src/experiments/setup.py --setup --schemes “indigo”
src/experiments/test.py local --schemes "indigo"
`then Then I copy the indigo folder,i meet the follow problem,
`Traceback (most recent call last):
  File "src/experiments/test.py", line 808, in main
    run_tests(args)
  File "src/experiments/test.py", line 749, in run_tests
    getattr(args, 'remote_path', None))
  File "/home/zouyong/pantheon/src/experiments/helpers/utils.py", line 180, in get_git_summary
    local_git_summary = check_output(git_summary_src, cwd=context.base_dir)
  File "/home/zouyong/pantheon/src/experiments/helpers/subprocess_wrappers.py", line 29, in check_output
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Error in tests!
`
How can I solve this problem，Looking forward to your answer！

**Comment by francisyyan** [comment]
Closing as this question is duplicate to https://github.com/StanfordSNR/indigo/issues/1.
